version: '3.7'

services:
  node:
    image: node:10-alpine
    container_name: graphql-vs-apollo_apollo_node
    env_file:
      - ${PWD}/.env
    user: node
    working_dir: /app
    volumes:
      - ${PWD}:/app
    ports:
      - ${PORT_APOLLO}:${PORT_APOLLO}
    command: sh -c "yarn install && yarn start"

  postgres:
    image: postgres:10-alpine
    container_name: ${POSTGRES_HOST}
    hostname: ${POSTGRES_HOST}
    env_file:
      - ${PWD}/.env
    volumes:
      - ${PWD}/docker/init-postgres.sh:/docker-entrypoint-initdb.d/init-posgres.sh
    ports:
      - ${POSTGRES_PORT_EXPOSE}:${POSTGRES_PORT_DOCKER}

  mongo:
    image: mongo:4
    container_name: ${MONGO_HOST}
    hostname: ${MONGO_HOST}
    env_file:
      - ${PWD}/.env
    volumes:
      - ${PWD}/docker/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - ${MONGO_PORT_EXPOSE}:${MONGO_PORT_DOCKER}
