#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
    CREATE DATABASE ${DB_GRAPHQL_DATABASE};
    CREATE USER ${DB_GRAPHQL_USER} WITH PASSWORD '${DB_GRAPHQL_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${DB_GRAPHQL_DATABASE} TO ${DB_GRAPHQL_USER};
    \connect ${DB_GRAPHQL_DATABASE};
    CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION ${DB_GRAPHQL_USER};

    CREATE DATABASE ${DB_APOLLO_DATABASE};
    CREATE USER ${DB_APOLLO_USER} WITH PASSWORD '${DB_APOLLO_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${DB_APOLLO_DATABASE} TO ${DB_APOLLO_USER};
    \connect ${DB_APOLLO_DATABASE};
    CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION ${DB_GRAPHQL_USER};
EOSQL