version: '3.7'

services:
  front:
    image: node:10-alpine
    container_name: graphql-vs-apollo_graphql_front
    env_file:
      - ${PWD}/FRONT/.env
    user: node
    volumes:
      - ${PWD}/FRONT:/app
    working_dir: /app
    ports:
      - 8081:8080
    command: sh -c "yarn install && yarn start"

  server:
    image: node:10-alpine
    container_name: graphql-vs-apollo_graphql_server
    env_file:
      - ${PWD}/SERVER/.env
    user: node
    working_dir: /app
    volumes:
      - ${PWD}/SERVER:/app
    ports:
      - ${PORT_GRAPHQL}:${PORT_GRAPHQL}
    command: sh -c "yarn install && yarn start"

  postgres:
    image: postgres:10-alpine
    container_name: ${POSTGRES_HOST}
    hostname: ${POSTGRES_HOST}
    env_file:
      - ${PWD}/SERVER/.env
    volumes:
      - ${PWD}/docker/init-postgres.sh:/docker-entrypoint-initdb.d/init-posgres.sh
    ports:
      - ${POSTGRES_PORT_EXPOSE}:${POSTGRES_PORT_DOCKER}

  mondo:
    image: mongo:4
    container_name: ${MONGO_HOST}
    hostname: ${MONGO_HOST}
    env_file:
      - ${PWD}/SERVER/.env
    volumes:
      - ${PWD}/docker/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - ${MONGO_PORT_EXPOSE}:${MONGO_PORT_DOCKER}
